version: '3.9'
services:
  app:
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - .:/app
      - python-packages:/root/.local/share
    ports:
      - "8501:8501"

volumes:
  python-packages:
