version: '3'
services:
  app:
    tty: true
    shm_size: '2gb'
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "9999:9999" # jupyter本体
        # - "9990:7860"
        # - "9991:7861"
        # - "9992:7862"
        #- "9993:7863"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_AUTH_TOKEN=${HUGGINGFACE_AUTH_TOKEN}
    volumes:
      - .:/app
      - python-packages:/root/.local/share
      - ~/.cache:/root/.cache
    # command:
      # tail -f /dev/null
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=9999
      --no-browser
      --NotebookApp.token='kazuph'
      --notebook-dir=/app

    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility, gpu]

volumes:
  python-packages:
    name: python-packages
    external: true
