version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8889:7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - .:/app
      - python-packages:/root/.local/share
      - hf-cache:/root/.cache
    command:
      # sleep endless
      tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

volumes:
  python-packages:
    name: python-packages
  hf-cache:
    name: hf-cache
